window.webConfigApi = {
  apiPath: 'https://admin.tkonline.cc',
  logoPath: 'https://stt.pwtk.cc/devmedia/photossys/guarantee/img/24/11/18/6452534cc56f4a86a754f89e0407c457.png',
  phone: '000-000-0000',
  whatsapp: '000-000-0000',
  facebook: 'https://www.facebook.com/',
  instagram: 'https://www.instagram.com/',
  PUBLIC_KV_URL: 'https://ocs.ai4funs.com/pwtkprd',
  VITE_PROXY_UPLOAD: 'https://upload.tkonline.cc',
  VITE_SERVER_CALLBACK: 'https://tk2cdn.ai4funs.com/',
  VITE_CDN_URL: 'https://tk2cdn.ai4funs.com/',
  VITE_STORY_TYPE: 'S3',
  VITE_STORAGE_BUCKET: 'prod',
  VITE_NODE_ENV: 'prod',
  VITE_CHAT_DOMAIN: 'https://vchat.bugacard.com:7089',
  VITE_PUBLIC_ENCRYPTION_URL: 'https://msecret.pwtk.cc',
  VITE_PUBLIC_AES_KEY_VERSION: '0',
  VITE_TASK_DOMAIN: 'https://prd-vbot.dating141.com',
  VITE_TASK_LIVE_DOMAIN: 'https://video-room-bot.pwtk.cc',
  VITE_AUDIO_CONVERT_TOOL_DOMAIN: 'https://towav.fastchatchat.com',
  version: '1.2.29',
  appName: '6gallery'
}
