window.webConfigApi = {
  apiPath: 'https://dev197.pwtk.cc',
  logoPath: 'https://stt.pwtk.cc/devmedia/photossys/guarantee/img/24/11/18/6452534cc56f4a86a754f89e0407c457.png',
  phone: '000-000-0000',
  whatsapp: '000-000-0000',
  facebook: 'https://www.facebook.com/',
  instagram: 'https://www.instagram.com/',
  PUBLIC_KV_URL: 'https://ocs.ai4funs.com/pwtk',
  VITE_PROXY_UPLOAD: 'https://upload.pwtk.cc',
  VITE_SERVER_CALLBACK: 'https://devmedia0.s3.ap-northeast-1.amazonaws.com/',
  VITE_CDN_URL: 'https://stt.pwtk.cc/',
  VITE_STORY_TYPE: 'S3',
  VITE_STORAGE_BUCKET: 'dev',
  VITE_NODE_ENV: 'development',
  VITE_CHAT_DOMAIN: 'https://vchat.pwtk.cc',
  VITE_PUBLIC_ENCRYPTION_URL: 'https://msecret.pwtk.cc',
  VITE_PUBLIC_AES_KEY_VERSION: '0',
  VITE_TASK_DOMAIN: 'https://voice-bot.dating141.com',
  VITE_TASK_LIVE_DOMAIN: 'https://video-room-bot.pwtk.cc',
  VITE_AUDIO_CONVERT_TOOL_DOMAIN: 'https://towav.pages.dev',
  version: '1.2.29',
  appName: '49gallery'
}
